name: int-tests

on:
  pull_request:
    branches: main
  workflow_dispatch:
    inputs:
      string_to_print:
        description: "Enter string to print"
        type: string
        required: false
        default: ''


jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - name: test
        id: print-test
        run: | 
          if [ ${{ inputs.string_to_print }} != '' ]; then
            echo "You entered: ${{ inputs.string_to_print }}"
          elif [ ${{ github.event }} == "pull_request" ]; then
            echo "This is a pull request!"
          else
            echo "you done messed up"
          fi