name: run-tests

on:
  pull_request:
    branches: main
  workflow_dispatch: {}

jobs:
  run-pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Setup Python 3.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.12.1

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run Pytest
        run: |
          poetry run pytest